apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    securityContext:
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
  securityContext:
    seccompProfile:
      type: RuntimeDefault
