apiVersion: v1
kind: Service
metadata:
  name: cpu-app-service
spec:
  selector:
    app: cpu-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
